
name: Deploy ARM Template

on:
  push:
    branches:
      - develop-**

jobs:
  deploy-virtual-network-template:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: Login to Azure
        uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./environments/develop/azuredeploy.json
          parameters: ./environments/develop/azuredeploy.parameters.dev.json