
name: Deploy ARM Template

on:
  push:
    branches:
      - develop-**

jobs:
  test:
    runs-on: ubuntu-latest
    environment: develop
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run what-if test
        working-directory: ./environments/develop
        run: |
          az deployment group what-if \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --template-file azuredeploy.json \
          --parameters azuredeploy.parameters.dev.json \
          --mode Complete \
          --no-pretty-print

  deploy:
    runs-on: ubuntu-latest
    environment: develop
    needs: test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./environments/develop/azuredeploy.json
          parameters: ./environments/develop/azuredeploy.parameters.dev.json
