
name: DEVELOP - Test and deploy

on:
  push:
    branches:
      - develop-**

jobs:

  test:
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          deploymentMode: Validate
          template: ./separated/azuredeploy.json
          parameters: ./separated/azuredeploy.parameters.json

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          deploymentMode: Incremental
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./separated/azuredeploy.json
          parameters: ./separated/azuredeploy.parameters.json
